import Head from 'next/head'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import { PostThumb, PostThumbProps } from '../components/PostThumb'
import { postThumbs } from '../lib/requests'

export const getStaticProps: GetStaticProps = async (context) => {
  const pt = await postThumbs()
  return {
    props: {
      postThumbs: pt
    }
  }
}

export default function Home({ postThumbs }: InferGetStaticPropsType<typeof getStaticProps>) {
  
  return (
    <>
      <Head>
        <title>Bits</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {postThumbs.map((props: PostThumbProps, idx: number) => (
            <PostThumb  key={props.id} {...props} />
        ))}

      </main>
    </>
  )
}
