import Head from 'next/head'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import { PostThumb, PostThumbProps } from '../components/PostThumb'
import { fetchPostThumbs } from '../lib/requests'

export const getStaticProps: GetStaticProps = async (context) => {
  const postThumbs = await fetchPostThumbs()
  return {
    props: {
      postThumbs
    }
  }
}

export default function Home({ postThumbs }: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"bg-red-100"}>
        {postThumbs.map((p: PostThumbProps) => <PostThumb {...p} />)}
      </main>
    </>
  )
}
